### PR TITLE
React Native update

### PR DESCRIPTION
**Pull request by hph**
This PR was opened because #254 was mistakenly closed.

### CODE REVIEW

**Comment by michaldudek** [comment]
Yup, this seems to do the trick 👍  All good in my project.

**Comment by hph** [comment]
Excellent, thanks for the feedback!

**Comment by michaldudek** [comment]
Great, thanks! Just waiting for tagged release now :)

**Comment by hph** [comment]
@michaldudek take a look at version 4.2.2 :)

**Pull request merged**
