### PR TITLE
Better documentation of bind_all methods

### PR DESCRIPTION
**Pull request by jameshfisher**
Following support request for documentation on how to use bind_all

### CODE REVIEW

**Comment by jameshfisher** [comment]
(When merging, we should also update the docs pages with this)

**Comment by jpatel531** [comment]
Sounds good - I'll do it tomorrow :)

**Comment by jackfranklin** [comment]
@jpatel531 bump!

**Comment by jackfranklin** [comment]
I should have mentioned this earlier, but long term I'd love to move from `bind_all` to `bindAll` for all snake case methods. We could do this in a way that could add a console warning but not be a breaking change.

**Pull request merged**
