### PR TITLE
replace main file with node pusher version instead of browser pusher …

### PR DESCRIPTION
**Pull request by mrbabbs**
What do you think to use this `package.json` for isomorphic module?
With this configuration, it is very easy to use the module in `node` and `browser` environment.

### CODE REVIEW

**Comment by jackfranklin** [comment]
👍  makes sense to me - this way it works both for Node use and browserify/webpack use by default. @jpatel531 wdyt?

**Comment by jpatel531** [comment]
Does the `"browser"` field also work for other types of bundler besides browserify? If so, I'd be happy to merge

**Comment by mrbabbs** [comment]
This configuration fixed the problem in my isomorphic module using [rollupjs](http://rollupjs.org/#{%22options%22%3A{%22format%22%3A%22cjs%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A{}}%2C%22modules%22%3A[{%22name%22%3A%22main.js%22%2C%22code%22%3A%22import%20{%20cube%20}%20from%20%27.%2Fmaths.js%27%3B\nconsole.log%28%20cube%28%205%20%29%20%29%3B%20%2F%2F%20125%22}%2C{%22name%22%3A%22maths.js%22%2C%22code%22%3A%22%2F%2F%20This%20function%20isn%27t%20used%20anywhere%2C%20so\n%2F%2F%20Rollup%20excludes%20it%20from%20the%20bundle...\nexport%20function%20square%20%28%20x%20%29%20{\n\treturn%20x%20*%20x%3B\n}\n\n%2F%2F%20This%20function%20gets%20included\nexport%20function%20cube%20%28%20x%20%29%20{\n\t%2F%2F%20rewrite%20this%20as%20%60square%28%20x%20%29%20*%20x%60\n\t%2F%2F%20and%20see%20what%20happens!\n\treturn%20x%20*%20x%20*%20x%3B\n}%22}]}).

**Comment by gabrielhpugliese** [comment]
Will this be merged?

**Comment by hph** [comment]
@gabrielhpugliese I have to take a better look at it first (to ensure it doesn't break anything, see if there's a better solution, etc). I'm going to release a new version within the next couple of days and I'll take a look at it before that, so I can include it if this is acceptable.

**Comment by hph** [comment]
Thanks for the input, this looks like the right approach. I've merged it into master.

**Pull request closed without merging**
