### PR TITLE
Basic encryption support for React Native

### PR DESCRIPTION
**Pull request by dmitrybirin**
## What does this PR do?

Hello! 👋 
For our React Native project we need to use the encrypted-channels feature, but it's not currently supported. So we decided to give it a push :)

My first implementation was more complex with changes in tweetnacl for random generating as well, but as I understand, pusher not using any methods of tweetnacl, that use randomBytes, so **main idea** ->  just drop the init of tweetnacl randomBytes completely on the webpack level.

Other changes:
- tweetnacl-util using stable packages for encoding/decoding as owner [suggests](https://github.com/dchest/tweetnacl-util-js/blob/master/README.md#notice)
- react native error dropped for the encryption channels (maybe we should put there some warning?)
- docs updated

Please, look at the main idea, if it's viable, I'll create react-native test suite as well.

## Checklist

- [ ] All new functionality has tests.
- [x] All tests are passing.
- [x] New or changed API methods have been documented.
- [ ] `npm run format` has been run

### CODE REVIEW

**Comment by leesio** [comment]
@dmitrybirin thanks so much for taking the time to do this work! I haven't had a lot of time to look into it yet, but it's definitely something we'd like to support.

**Comment by leesio** [comment]
@gmrchk hey, sorry for the delay in getting back to you.

The next thing I'll be implementing in pusher-js is the ability to inject the nacl dependency into the library as part of the configuration. We'll be removing the bundled nacl library completely. We've decided on this approach for a couple of reasons:

- to reduce the size of the bundled javascript artefact
- to support e2ee in react-native

Since this functionality will be coming soon, I'm going to hold off merging this PR.

I realise this may be a little frustrating, since you've spent time and effort on it. Hopefully that's balanced a little bit by the fact that support for react-native (via an injected nacl lib) is coming soon.

Sorry again for the delay in communicating it. This has been a pending decision internally for a little while and I didn't want to come back until I had more information.

**Comment by dmitrybirin** [comment]
@leesio Thanks for the update! Well, I think it will be even easier for us, if there will be some configuration to inject the nacl dependency.
Is it possible for us to monitor your progress/help if needed? I mean, will be some PR in this repo?

**Comment by leesio** [comment]
That's great to hear!

In terms of monitoring the progress, I'll be working on it out in the open. I'll be sure to drop a message in this issue when I push the first commit. I'll definitely be glad of feedback.

**Comment by leesio** [comment]
@gmrchk @dmitrybirin I started work on this this afternoon, you can see the draft PR here #445

**Comment by leesio** [comment]
@gmrchk @dmitrybirin I continued work on the above PR and, in the end, I think I found a reasonable way to support encrypted channels in react-native. 

The PR is here https://github.com/pusher/pusher-js/pull/447. I wonder whether you'd be interested in trying a build to see if it works in your app?

**Comment by gmrchk** [comment]
Hey @leesio, that's awesome to hear. We see that you already announced the out-of-beta for e2e encryption, which is terrific!

We're busy with things at the moment, but we should get to testing this out soon (maybe next week). We'll be sure to post feedback.

**Comment by dmitrybirin** [comment]
@leesio sorry, that haven't answer you earlier, totally missed github notifications 🤦
Thank you for your great work 👍  I just check your implementation with our app, works like a charm.

Maybe for the future wonderers 👇 
As I understand from the implementation, you're shipping tweetnacl part you need with the bundle, not relying on the particular nasty IIFE with `crypto` on React Native bundle: https://github.com/dchest/tweetnacl-js/blob/f1ec050ceae0861f34280e62498b1d3ed9c350c6/nacl-fast.js#L2363
Thats totally works for us.

When I'm trying to understand why everything working now :) I've noticed couple of small things in docs and dead code regarding RN. Will add PRs soon, if that's ok.

As for that particular PR, I think we can close it 🎉  Thank you again!

**Pull request closed without merging**
