### PR TITLE
Dont swallow connected exceptions

### PR DESCRIPTION
**Pull request by Serya05**

### CODE REVIEW

**Comment by leggetter** [comment]
Closing. Fixed in https://github.com/pusher/pusher-js/commit/b02529cd845771435ef3e1efe271e227cf733d63

**Comment by leggetter** [comment]
Actually, @pl - what is the status of this?

**Comment by pl** [comment]
That commit was not merged into `master`, but we should integrate it into 3.0. Catching exceptions from that callback is a bit of a pain.

**Comment by jpatel531** [comment]
@pl  - i can integrate this into the next release? it's essentially what i was talking about earlier - e.g. passing `'yolo'` to `authTransports` bubbles up the errors and leads to handshake errors

**Comment by pl** [comment]
Yes, it would be great if it was merged.

**Comment by jpatel531** [comment]
Closing as moved to: https://github.com/pusher-community/pusher-websocket-js-iso/pull/6

**Pull request closed without merging**
